name: Update Version Number
permissions:
  contents: write
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update version and date in README_en.md
        run: |
          # 计算版本号（基于 commit 次数）
          COMMIT_COUNT=$(git rev-list --count HEAD)
          VERSION="v0.$COMMIT_COUNT.0"
          # 更新版本号
          sed -i "s/<!-- VERSION_PLACEHOLDER -->/$VERSION/g" README.md
          # 更新日期
          DATE=$(date '+%Y-%m-%d')
          sed -i "s/<!-- DATE_PLACEHOLDER -->/$DATE/g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update version to $VERSION and date to $DATE" || echo "No changes to commit"
          git push
