name: Update Version Number

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update version in README.md
        run: |
          # 计算版本号（例如基于 commit 次数）
          COMMIT_COUNT=$(git rev-list --count HEAD)
          VERSION="v0.$COMMIT_COUNT.0"
          sed -i "s/<!-- VERSION_PLACEHOLDER -->/$VERSION/g" README.md
          # 更新日期
          DATE=$(date '+%Y-%m-%d')
          sed -i "s/Updated: March 23, 2025/Updated: $DATE/g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update version to $VERSION" || echo "No changes to commit"
          git push
